// Code generated by xgen. DO NOT EDIT.

package main

// MessageType ...
type MessageType struct {
	AppHdr   *BusinessApplicationHeaderV01 `xml:"AppHdr"`
	Document *Document                     `xml:"Document"`
}

// Document ...
type Document struct {
	FIToFICstmrCdtTrf *FIToFICustomerCreditTransferV08       `xml:"FIToFICstmrCdtTrf"`
	FICdtTrf          *FinancialInstitutionCreditTransferV09 `xml:"FICdtTrf"`
	FIToFIPmtStsRpt   *FIToFIPaymentStatusReportV10          `xml:"FIToFIPmtStsRpt"`
	FIToFIPmtStsReq   *FIToFIPaymentStatusRequestV04         `xml:"FIToFIPmtStsReq"`
	MessageReject     *MessageRejectV01                      `xml:"MessageReject"`
	SysEvtNtfctn      *SystemEventNotificationV02            `xml:"SysEvtNtfctn"`
	SysEvtAck         *SystemEventAcknowledgementV01         `xml:"SysEvtAck"`
	AdmnReq           *AdmnRequestV01                        `xml:"AdmnReq"`
	AdmnResp          *AdmnResponseV01                       `xml:"AdmnResp"`
	PrxyRegn          *ProxyRegistrationV01                  `xml:"PrxyRegn"`
	PrxyRegnRspn      *ProxyRegistrationResponseV01          `xml:"PrxyRegnRspn"`
	PrxyLookUp        *ProxyLookUpV01                        `xml:"PrxyLookUp"`
	PrxyLookUpRspn    *ProxyLookUpResponseV01                `xml:"PrxyLookUpRspn"`
	PrxyNqryReq       *ProxyEnquiryV01                       `xml:"PrxyNqryReq"`
	PrxyNqryRspn      *ProxyEnquiryResponseV01               `xml:"PrxyNqryRspn"`
	PrxyNtfctn        *ProxyNtfctnV01                        `xml:"PrxyNtfctn"`
}

// BusMsg ...
type BusMsg *MessageType
