// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"time"
)

// Document ...
type Document *Document

// Event2 is x
type Event2 struct {
	EvtCd    string    `xml:"EvtCd"`
	EvtParam []string  `xml:"EvtParam"`
	EvtDesc  string    `xml:"EvtDesc"`
	EvtTm    time.Time `xml:"EvtTm"`
}

// ISODateTime ...
type ISODateTime time.Time

// Max1000Text ...
type Max1000Text string

// Max35Text ...
type Max35Text string

// Max4AlphaNumericText ...
type Max4AlphaNumericText string

// SystemEventNotificationV02 is x
type SystemEventNotificationV02 struct {
	EvtInf *Event2 `xml:"EvtInf"`
}
