// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"time"
)

// Document ...
type Document *Document

// Event1 is x
type Event1 struct {
	EvtCd    string    `xml:"EvtCd"`
	EvtParam []string  `xml:"EvtParam"`
	EvtDesc  string    `xml:"EvtDesc"`
	EvtTm    time.Time `xml:"EvtTm"`
}

// Exact4AlphaNumericText ...
type Exact4AlphaNumericText string

// ISODateTime ...
type ISODateTime time.Time

// Max350Text ...
type Max350Text string

// Max35Text ...
type Max35Text string

// Max4AlphaNumericText ...
type Max4AlphaNumericText string

// SupplementaryData1 is Supplementary data Envelope
type SupplementaryData1 struct {
	PlcAndNm string                      `xml:"PlcAndNm"`
	Envlp    *SupplementaryDataEnvelope1 `xml:"Envlp"`
}

// SupplementaryDataEnvelope1 ...
type SupplementaryDataEnvelope1 struct {
}

// SystemEventAcknowledgementV01 is Supplementary Data group
type SystemEventAcknowledgementV01 struct {
	MsgId       string                `xml:"MsgId"`
	OrgtrRef    string                `xml:"OrgtrRef"`
	SttlmSsnIdr string                `xml:"SttlmSsnIdr"`
	AckDtls     *Event1               `xml:"AckDtls"`
	SplmtryData []*SupplementaryData1 `xml:"SplmtryData"`
}
