// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"time"
)

// AddressType2Code ...
type AddressType2Code string

// AdmnResp is x
type AdmnResp struct {
	InstgAgt     *BranchAndFinancialInstitutionIdentification5 `xml:"InstgAgt"`
	OrgnlInstrId string                                        `xml:"OrgnlInstrId"`
	FnctnCd      string                                        `xml:"FnctnCd"`
	TxSts        string                                        `xml:"TxSts"`
}

// AdmnResponseV01 is x
type AdmnResponseV01 struct {
	GrpHdr       *GrpHdr   `xml:"GrpHdr"`
	AdmnResponse *AdmnResp `xml:"AdmnResponse"`
}

// BICFIIdentifier ...
type BICFIIdentifier string

// BranchAndFinancialInstitutionIdentification5 is x
type BranchAndFinancialInstitutionIdentification5 struct {
	FinInstnId *FinancialInstitutionIdentification8 `xml:"FinInstnId"`
	BrnchId    *BranchData2                         `xml:"BrnchId"`
}

// BranchData2 ...
type BranchData2 struct {
	Id      string          `xml:"Id"`
	Nm      string          `xml:"Nm"`
	PstlAdr *PostalAddress6 `xml:"PstlAdr"`
}

// ClearingSystemMemberIdentification2 ...
type ClearingSystemMemberIdentification2 struct {
	BICFI string `xml:"BICFI"`
}

// CountryCode ...
type CountryCode string

// Document is x
type Document struct {
	AdmnResp *AdmnResponseV01 `xml:"AdmnResp"`
}

// EventCode ...
type EventCode string

// ExternalFinancialInstitutionIdentification1Code ...
type ExternalFinancialInstitutionIdentification1Code string

// FinancialIdentificationSchemeName1Choice ...
type FinancialIdentificationSchemeName1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// FinancialInstitutionIdentification8 is x
type FinancialInstitutionIdentification8 struct {
	BICFI       string                               `xml:"BICFI"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"ClrSysMmbId"`
	Nm          string                               `xml:"Nm"`
	PstlAdr     *PostalAddress6                      `xml:"PstlAdr"`
	Othr        *GenericFinancialIdentification1     `xml:"Othr"`
}

// GenericFinancialIdentification1 is x
type GenericFinancialIdentification1 struct {
	Id      string                                    `xml:"Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"SchmeNm"`
	Issr    string                                    `xml:"Issr"`
}

// GrpHdr is x
type GrpHdr struct {
	MsgId   string    `xml:"MsgId"`
	CreDtTm time.Time `xml:"CreDtTm"`
}

// ISODateTime ...
type ISODateTime time.Time

// Max140Text ...
type Max140Text string

// Max16Text ...
type Max16Text string

// Max35Text ...
type Max35Text string

// Max70Text ...
type Max70Text string

// Min11Max11Text ...
type Min11Max11Text string

// PostalAddress6 ...
type PostalAddress6 struct {
	AdrTp       string   `xml:"AdrTp"`
	Dept        string   `xml:"Dept"`
	SubDept     string   `xml:"SubDept"`
	StrtNm      string   `xml:"StrtNm"`
	BldgNb      string   `xml:"BldgNb"`
	PstCd       string   `xml:"PstCd"`
	TwnNm       string   `xml:"TwnNm"`
	CtrySubDvsn string   `xml:"CtrySubDvsn"`
	Ctry        string   `xml:"Ctry"`
	AdrLine     []string `xml:"AdrLine"`
}

// TransactionIndividualStatus3CodeAdmn ...
type TransactionIndividualStatus3CodeAdmn string
