// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
	"time"
)

// AccountIdentification4Choice is x
type AccountIdentification4Choice struct {
	Othr *GenericAccountIdentification1 `xml:"Othr"`
}

// AddressType2Code ...
type AddressType2Code string

// BICFIIdentifier ...
type BICFIIdentifier string

// BranchAndFinancialInstitutionIdentification5 is x
type BranchAndFinancialInstitutionIdentification5 struct {
	FinInstnId *FinancialInstitutionIdentification8 `xml:"FinInstnId"`
	BrnchId    *BranchData2                         `xml:"BrnchId"`
}

// BranchData2 ...
type BranchData2 struct {
	Id      string          `xml:"Id"`
	Nm      string          `xml:"Nm"`
	PstlAdr *PostalAddress6 `xml:"PstlAdr"`
}

// CashAccount40 is Not used by BI
type CashAccount40 struct {
	Id         *AccountIdentification4Choice `xml:"Id"`
	Tp         *CashAccountType2ChoiceProxy  `xml:"Tp"`
	Nm         string                        `xml:"Nm"`
	AcctHldrTp string                        `xml:"AcctHldrTp"`
}

// CashAccountType2ChoiceProxy is x
type CashAccountType2ChoiceProxy struct {
	Prtry string `xml:"Prtry"`
}

// ClearingSystemMemberIdentification2 ...
type ClearingSystemMemberIdentification2 struct {
	BICFI string `xml:"BICFI"`
}

// CountryCode ...
type CountryCode string

// Document is x
type Document struct {
	PrxyRegn *ProxyRegistrationV01 `xml:"PrxyRegn"`
}

// Exact4AlphaNumericText ...
type Exact4AlphaNumericText string

// ExternalFinancialInstitutionIdentification1Code ...
type ExternalFinancialInstitutionIdentification1Code string

// FinancialIdentificationSchemeName1Choice ...
type FinancialIdentificationSchemeName1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// FinancialInstitutionIdentification8 is x
type FinancialInstitutionIdentification8 struct {
	BICFI       string                               `xml:"BICFI"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"ClrSysMmbId"`
	Nm          string                               `xml:"Nm"`
	PstlAdr     *PostalAddress6                      `xml:"PstlAdr"`
	Othr        *GenericFinancialIdentification1     `xml:"Othr"`
}

// GenericFinancialIdentification1 is x
type GenericFinancialIdentification1 struct {
	Id      string                                    `xml:"Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"SchmeNm"`
	Issr    string                                    `xml:"Issr"`
}

// GenericAccountIdentification1 is x
type GenericAccountIdentification1 struct {
	Id string `xml:"Id"`
}

// GenericIdentification47 is Organisation Identifier issuer code
type GenericIdentification47 struct {
	Id   string `xml:"Id"`
	Issr string `xml:"Issr"`
}

// GroupHeader59 is x
type GroupHeader59 struct {
	MsgId   string         `xml:"MsgId"`
	CreDtTm time.Time      `xml:"CreDtTm"`
	MsgSndr *Party12Choice `xml:"MsgSndr"`
}

// IndividualPerson28 ...
type IndividualPerson28 struct {
	GvnNm  string `xml:"GvnNm"`
	MddlNm string `xml:"MddlNm"`
	Nm     string `xml:"Nm"`
}

// ISODate ...
type ISODate time.Time

// ISODateTime ...
type ISODateTime time.Time

// Max12Text ...
type Max12Text string

// Max140Text ...
type Max140Text string

// Max16Text ...
type Max16Text string

// Max34Text ...
type Max34Text string

// Max350Text ...
type Max350Text string

// Max35Text ...
type Max35Text string

// Max4AlphaNumericText ...
type Max4AlphaNumericText string

// Max70Text ...
type Max70Text string

// Min11Max11Text ...
type Min11Max11Text string

// Organisation22 is Account holder Organisation Type of Org info group
type Organisation22 struct {
	Nm      string                   `xml:"Nm"`
	RegnDt  time.Time                `xml:"RegnDt"`
	TpOfOrg *OrganisationType1Choice `xml:"TpOfOrg"`
}

// OrganisationType1Choice is Account holder Organisation Type of Org Proprietory identifier info group
type OrganisationType1Choice struct {
	Prtry *GenericIdentification47 `xml:"Prtry"`
}

// Party12Choice is x
type Party12Choice struct {
	Agt *BranchAndFinancialInstitutionIdentification5 `xml:"Agt"`
}

// Party30Choice is Account holder Organisation info group
type Party30Choice struct {
	Org      *Organisation22     `xml:"Org"`
	IndvPrsn *IndividualPerson28 `xml:"IndvPrsn"`
}

// PostalAddress6 ...
type PostalAddress6 struct {
	AdrTp       string   `xml:"AdrTp"`
	Dept        string   `xml:"Dept"`
	SubDept     string   `xml:"SubDept"`
	StrtNm      string   `xml:"StrtNm"`
	BldgNb      string   `xml:"BldgNb"`
	PstCd       string   `xml:"PstCd"`
	TwnNm       string   `xml:"TwnNm"`
	CtrySubDvsn string   `xml:"CtrySubDvsn"`
	Ctry        string   `xml:"Ctry"`
	AdrLine     []string `xml:"AdrLine"`
}

// ProxyAccountType ...
type ProxyAccountType string

// ProxyDefinition1 is Validate phone number as 62\d+ (62xxxx...), Validate email address as [^@]+@[^@]+] (xxxx@xxxx)
type ProxyDefinition1 struct {
	Tp  string `xml:"Tp"`
	Val string `xml:"Val"`
}

// ProxyRegistration1 is x
type ProxyRegistration1 struct {
	RegnTp    string                     `xml:"RegnTp"`
	RegnSubTp string                     `xml:"RegnSubTp"`
	Prxy      *ProxyDefinition1          `xml:"Prxy"`
	PrxyRegn  *ProxyRegistrationAccount1 `xml:"PrxyRegn"`
}

// ProxyRegistrationAccount1 is Pre-Authorised - indicator of whether proxy info is pre-authorised
type ProxyRegistrationAccount1 struct {
	RegnId     string                                        `xml:"RegnId"`
	DsplNm     string                                        `xml:"DsplNm"`
	Agt        *BranchAndFinancialInstitutionIdentification5 `xml:"Agt"`
	Acct       *CashAccount40                                `xml:"Acct"`
	AcctHldr   *Party30Choice                                `xml:"AcctHldr"`
	ScndId     *ScndIdDefinition1                            `xml:"ScndId"`
	RegnSts    string                                        `xml:"RegnSts"`
	PreAuthrsd bool                                          `xml:"PreAuthrsd"`
}

// ProxyRegistrationStatusCode ...
type ProxyRegistrationStatusCode string

// ProxyRegistrationSubType1Code ...
type ProxyRegistrationSubType1Code string

// ProxyRegistrationType1Code ...
type ProxyRegistrationType1Code string

// ProxyRegistrationV01 is x
type ProxyRegistrationV01 struct {
	GrpHdr      *GroupHeader59          `xml:"GrpHdr"`
	Regn        *ProxyRegistration1     `xml:"Regn"`
	SplmtryData []*BISupplementaryData1 `xml:"SplmtryData"`
}

// ScndIdDefinition1 is x
type ScndIdDefinition1 struct {
	Tp  string `xml:"Tp"`
	Val string `xml:"Val"`
}

// YesNoIndicator ...
type YesNoIndicator bool

// BISupplementaryData1 is x
type BISupplementaryData1 struct {
	XMLName  xml.Name                      `xml:"BI_SupplementaryData1"`
	PlcAndNm string                        `xml:"PlcAndNm"`
	Envlp    *BISupplementaryDataEnvelope1 `xml:"Envlp"`
}

// BISupplementaryDataEnvelope1 is Supplementary customer info group for Customer
type BISupplementaryDataEnvelope1 struct {
	XMLName xml.Name         `xml:"BI_SupplementaryDataEnvelope1"`
	Cstmr   *BIAddtlCstmrInf `xml:"Cstmr"`
}

// BIAddtlCstmrInf is [PS: Customer's Hometown]
type BIAddtlCstmrInf struct {
	XMLName  xml.Name `xml:"BI_AddtlCstmrInf"`
	Tp       string   `xml:"Tp"`
	Id       string   `xml:"Id"`
	RsdntSts string   `xml:"RsdntSts"`
	TwnNm    string   `xml:"TwnNm"`
}
