// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
	"time"
)

// AccountIdentification4Choice is x
type AccountIdentification4Choice struct {
	Othr *GenericAccountIdentification1 `xml:"Othr"`
}

// AddressType2Code ...
type AddressType2Code string

// BICFIIdentifier ...
type BICFIIdentifier string

// BranchAndFinancialInstitutionIdentification5 is x
type BranchAndFinancialInstitutionIdentification5 struct {
	FinInstnId *FinancialInstitutionIdentification8 `xml:"FinInstnId"`
	BrnchId    *BranchData2                         `xml:"BrnchId"`
}

// BranchData2 ...
type BranchData2 struct {
	Id      string          `xml:"Id"`
	Nm      string          `xml:"Nm"`
	PstlAdr *PostalAddress6 `xml:"PstlAdr"`
}

// CashAccount40 is x
type CashAccount40 struct {
	Id *AccountIdentification4Choice `xml:"Id"`
	Tp *CashAccountType2ChoiceProxy  `xml:"Tp"`
	Nm string                        `xml:"Nm"`
}

// CashAccountType2ChoiceProxy is x
type CashAccountType2ChoiceProxy struct {
	Prtry string `xml:"Prtry"`
}

// ClearingSystemMemberIdentification2 ...
type ClearingSystemMemberIdentification2 struct {
	BICFI string `xml:"BICFI"`
}

// CountryCode ...
type CountryCode string

// Document is x
type Document struct {
	PrxyNtfctn *ProxyNtfctnV01 `xml:"PrxyNtfctn"`
}

// ExternalFinancialInstitutionIdentification1Code ...
type ExternalFinancialInstitutionIdentification1Code string

// ExternalStatusReason1Code ...
type ExternalStatusReason1Code string

// FinancialIdentificationSchemeName1Choice ...
type FinancialIdentificationSchemeName1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// FinancialInstitutionIdentification8 is x
type FinancialInstitutionIdentification8 struct {
	BICFI       string                               `xml:"BICFI"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"ClrSysMmbId"`
	Nm          string                               `xml:"Nm"`
	PstlAdr     *PostalAddress6                      `xml:"PstlAdr"`
	Othr        *GenericFinancialIdentification1     `xml:"Othr"`
}

// GenericAccountIdentification1 is x
type GenericAccountIdentification1 struct {
	Id string `xml:"Id"`
}

// GenericFinancialIdentification1 is x
type GenericFinancialIdentification1 struct {
	Id      string                                    `xml:"Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"SchmeNm"`
	Issr    string                                    `xml:"Issr"`
}

// GroupHeader60 is x
type GroupHeader60 struct {
	MsgId   string         `xml:"MsgId"`
	CreDtTm time.Time      `xml:"CreDtTm"`
	MsgRcpt *Party12Choice `xml:"MsgRcpt"`
}

// ISODateTime ...
type ISODateTime time.Time

// Max12Text ...
type Max12Text string

// Max140Text ...
type Max140Text string

// Max16Text ...
type Max16Text string

// Max34Text ...
type Max34Text string

// Max35Text ...
type Max35Text string

// Max70Text ...
type Max70Text string

// Min11Max11Text ...
type Min11Max11Text string

// OriginalGroupInformation3 ...
type OriginalGroupInformation3 struct {
	OrgnlMsgId   string    `xml:"OrgnlMsgId"`
	OrgnlMsgNmId string    `xml:"OrgnlMsgNmId"`
	OrgnlCreDtTm time.Time `xml:"OrgnlCreDtTm"`
}

// Party12Choice is x
type Party12Choice struct {
	Agt *BranchAndFinancialInstitutionIdentification5 `xml:"Agt"`
}

// PostalAddress6 ...
type PostalAddress6 struct {
	AdrTp       string   `xml:"AdrTp"`
	Dept        string   `xml:"Dept"`
	SubDept     string   `xml:"SubDept"`
	StrtNm      string   `xml:"StrtNm"`
	BldgNb      string   `xml:"BldgNb"`
	PstCd       string   `xml:"PstCd"`
	TwnNm       string   `xml:"TwnNm"`
	CtrySubDvsn string   `xml:"CtrySubDvsn"`
	Ctry        string   `xml:"Ctry"`
	AdrLine     []string `xml:"AdrLine"`
}

// ProxyAccountType ...
type ProxyAccountType string

// ProxyDefinition1 is x
type ProxyDefinition1 struct {
	Tp  string `xml:"Tp"`
	Val string `xml:"Val"`
}

// ProxyAccount1 is x
type ProxyAccount1 struct {
	RegnId      string                                        `xml:"RegnId"`
	DsplNm      string                                        `xml:"DsplNm"`
	Agt         *BranchAndFinancialInstitutionIdentification5 `xml:"Agt"`
	Acct        *CashAccount40                                `xml:"Acct"`
	SplmtryData []*BISupplementaryData1                       `xml:"SplmtryData"`
}

// ProxyNtfctn1 is x
type ProxyNtfctn1 struct {
	OrgnlId   string            `xml:"OrgnlId"`
	OrgnlPrxy *ProxyDefinition1 `xml:"OrgnlPrxy"`
	OrgnlAcct *ProxyAccount1    `xml:"OrgnlAcct"`
	NewAcct   *ProxyAccount1    `xml:"NewAcct"`
}

// ProxyNtfctnV01 is x
type ProxyNtfctnV01 struct {
	GrpHdr *GroupHeader60 `xml:"GrpHdr"`
	Ntfctn *ProxyNtfctn1  `xml:"Ntfctn"`
}

// ProxyStatusChoice ...
type ProxyStatusChoice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// ProxyStatusCode ...
type ProxyStatusCode string

// YesNoIndicator ...
type YesNoIndicator bool

// BIMax350Text ...
type BIMax350Text string

// BISupplementaryData1 is x
type BISupplementaryData1 struct {
	XMLName  xml.Name                      `xml:"BI_SupplementaryData1"`
	PlcAndNm string                        `xml:"PlcAndNm"`
	Envlp    *BISupplementaryDataEnvelope1 `xml:"Envlp"`
}

// BISupplementaryDataEnvelope1 is x
type BISupplementaryDataEnvelope1 struct {
	XMLName xml.Name         `xml:"BI_SupplementaryDataEnvelope1"`
	Cstmr   *BIAddtlCstmrInf `xml:"Cstmr"`
}

// BIAddtlCstmrInf is [PS: Customer's Hometown]
type BIAddtlCstmrInf struct {
	XMLName  xml.Name `xml:"BI_AddtlCstmrInf"`
	Tp       string   `xml:"Tp"`
	Id       string   `xml:"Id"`
	RsdntSts string   `xml:"RsdntSts"`
	TwnNm    string   `xml:"TwnNm"`
}
