// Code generated by xgen. DO NOT EDIT.

package schema

import (
	"encoding/xml"
	"time"
)

// AddressType2Code ...
type AddressType2Code string

// BICFIIdentifier ...
type BICFIIdentifier string

// BranchAndFinancialInstitutionIdentification5 is x
type BranchAndFinancialInstitutionIdentification5 struct {
	FinInstnId *FinancialInstitutionIdentification8 `xml:"FinInstnId"`
	BrnchId    *BranchData2                         `xml:"BrnchId"`
}

// BranchData2 ...
type BranchData2 struct {
	Id      string          `xml:"Id"`
	Nm      string          `xml:"Nm"`
	PstlAdr *PostalAddress6 `xml:"PstlAdr"`
}

// ClearingSystemMemberIdentification2 ...
type ClearingSystemMemberIdentification2 struct {
	BICFI string `xml:"BICFI"`
}

// CountryCode ...
type CountryCode string

// Document is x
type Document struct {
	PrxyRegnRspn *ProxyRegistrationResponseV01 `xml:"PrxyRegnRspn"`
}

// ExternalFinancialInstitutionIdentification1Code ...
type ExternalFinancialInstitutionIdentification1Code string

// ExternalStatusReason1Code ...
type ExternalStatusReason1Code string

// FinancialIdentificationSchemeName1Choice ...
type FinancialIdentificationSchemeName1Choice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// FinancialInstitutionIdentification8 is x
type FinancialInstitutionIdentification8 struct {
	BICFI       string                               `xml:"BICFI"`
	ClrSysMmbId *ClearingSystemMemberIdentification2 `xml:"ClrSysMmbId"`
	Nm          string                               `xml:"Nm"`
	PstlAdr     *PostalAddress6                      `xml:"PstlAdr"`
	Othr        *GenericFinancialIdentification1     `xml:"Othr"`
}

// GenericFinancialIdentification1 is x
type GenericFinancialIdentification1 struct {
	Id      string                                    `xml:"Id"`
	SchmeNm *FinancialIdentificationSchemeName1Choice `xml:"SchmeNm"`
	Issr    string                                    `xml:"Issr"`
}

// GroupHeader60 is x
type GroupHeader60 struct {
	MsgId   string         `xml:"MsgId"`
	CreDtTm time.Time      `xml:"CreDtTm"`
	MsgRcpt *Party12Choice `xml:"MsgRcpt"`
}

// ISODateTime ...
type ISODateTime time.Time

// Max12Text ...
type Max12Text string

// Max140Text ...
type Max140Text string

// Max16Text ...
type Max16Text string

// Max35Text ...
type Max35Text string

// Max70Text ...
type Max70Text string

// Min11Max11Text ...
type Min11Max11Text string

// OriginalGroupInformation3 is x
type OriginalGroupInformation3 struct {
	OrgnlMsgId   string    `xml:"OrgnlMsgId"`
	OrgnlMsgNmId string    `xml:"OrgnlMsgNmId"`
	OrgnlCreDtTm time.Time `xml:"OrgnlCreDtTm"`
}

// Party12Choice is x
type Party12Choice struct {
	Agt *BranchAndFinancialInstitutionIdentification5 `xml:"Agt"`
}

// PostalAddress6 ...
type PostalAddress6 struct {
	AdrTp       string   `xml:"AdrTp"`
	Dept        string   `xml:"Dept"`
	SubDept     string   `xml:"SubDept"`
	StrtNm      string   `xml:"StrtNm"`
	BldgNb      string   `xml:"BldgNb"`
	PstCd       string   `xml:"PstCd"`
	TwnNm       string   `xml:"TwnNm"`
	CtrySubDvsn string   `xml:"CtrySubDvsn"`
	Ctry        string   `xml:"Ctry"`
	AdrLine     []string `xml:"AdrLine"`
}

// ProxyDefinition1 ...
type ProxyDefinition1 struct {
	Tp  string `xml:"Tp"`
	Val string `xml:"Val"`
}

// ProxyRegistrationAccount1 is x
type ProxyRegistrationAccount1 struct {
	RegnId      string                                        `xml:"RegnId"`
	Agt         *BranchAndFinancialInstitutionIdentification5 `xml:"Agt"`
	SplmtryData []*BISupplementaryData1                       `xml:"SplmtryData"`
}

// ProxyRegistrationResponse1 is x
type ProxyRegistrationResponse1 struct {
	PrxRspnSts     string                       `xml:"PrxRspnSts"`
	StsRsnInf      *ProxyStatusChoice           `xml:"StsRsnInf"`
	OrgnlRegnTp    string                       `xml:"OrgnlRegnTp"`
	OrgnlRegnSubTp string                       `xml:"OrgnlRegnSubTp"`
	OrgnlPrxy      *ProxyDefinition1            `xml:"OrgnlPrxy"`
	PrxyRegn       []*ProxyRegistrationAccount1 `xml:"PrxyRegn"`
}

// ProxyRegistrationResponseV01 is x
type ProxyRegistrationResponseV01 struct {
	GrpHdr      *GroupHeader60              `xml:"GrpHdr"`
	OrgnlGrpInf *OriginalGroupInformation3  `xml:"OrgnlGrpInf"`
	RegnRspn    *ProxyRegistrationResponse1 `xml:"RegnRspn"`
}

// ProxyRegistrationSubType1Code ...
type ProxyRegistrationSubType1Code string

// ProxyRegistrationType1Code ...
type ProxyRegistrationType1Code string

// ProxyStatusChoice is x
type ProxyStatusChoice struct {
	Cd    string `xml:"Cd"`
	Prtry string `xml:"Prtry"`
}

// ProxyStatusCode ...
type ProxyStatusCode string

// BIMax350Text ...
type BIMax350Text string

// BISupplementaryData1 is x
type BISupplementaryData1 struct {
	XMLName  xml.Name                      `xml:"BI_SupplementaryData1"`
	PlcAndNm string                        `xml:"PlcAndNm"`
	Envlp    *BISupplementaryDataEnvelope1 `xml:"Envlp"`
}

// BISupplementaryDataEnvelope1 is x
type BISupplementaryDataEnvelope1 struct {
	XMLName xml.Name         `xml:"BI_SupplementaryDataEnvelope1"`
	Cstmr   *BIAddtlCstmrInf `xml:"Cstmr"`
}

// BIAddtlCstmrInf is [PS: Customer's Hometown]
type BIAddtlCstmrInf struct {
	XMLName  xml.Name `xml:"BI_AddtlCstmrInf"`
	Tp       string   `xml:"Tp"`
	Id       string   `xml:"Id"`
	RsdntSts string   `xml:"RsdntSts"`
	TwnNm    string   `xml:"TwnNm"`
}
